title:            Sirius Blog
description:      Блог Сергея Хацёла
disqus_shortname: 
reading_time:     true
words_per_minute: 200

# Your site's domain goes here (eg: https://mmistakes.github.io, etc) OR When testing locally leave blank
url:

# Owner/author information
owner:
  name:           Sergey Khatsiola
  avatar:         avatar.jpg
  bio:            "Кратко обо мне ..."
  email:          2hotab2@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        2hotab2
  facebook:       sergej.ha1
  github:         Sergey-sirius
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages matrix.jpg
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-130427752-1   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

mermaid:
  src: "/js/mermaid.js"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Kiev
future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin
  - jekyll-mermaid
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed

mermaid:
    src: '/js/mermaid.js'

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
